# .npmcheckrc

depcheck:
  ignoreMatches:
    [
      "postcss",
      "autoprefixer",
      "typescript",
      "@types/node",
      "tailwindcss",
      "tw-animate-css",
      "@hookform/resolvers",
      "@tailwindcss/postcss",
    ]
